### ISSUE TITLE
pty_shell bug in p3

### ISSUE THREAD

**Issue by mturilli** [radical-cybertools/radical.saga#747]
```$ radical-stack 

  python               : 3.5.2
  pythonpath           : 
  virtualenv           : /home/mturilli/Virtualenvs/stampede2-p3

  radical.pilot        : 0.90.1-v0.90.1-44-gbcf9a01f@devel
  radical.saga         : 0.90.0-bv0.72.0-35-gf3a22201@devel
  radical.utils        : 0.90.3-v0.90.3-91-gf7dd7f6@devel
```
Running `heterogeneous.py` against `stampede2_ssh` I get the following trace:

```Traceback (most recent call last):
  File "./heterogeneous.py", line 25, in <module>
    pilot = pmgr.submit_pilots(pdesc)
  File "/home/mturilli/Virtualenvs/stampede2-p3/lib/python3.5/site-packages/radical/pilot/pilot_manager.py", line 502, in submit_pilots
    pilot = ComputePilot(pmgr=self, descr=pd)
  File "/home/mturilli/Virtualenvs/stampede2-p3/lib/python3.5/site-packages/radical/pilot/compute_pilot.py", line 102, in __init__
    self._resource_sandbox = self._session._get_resource_sandbox(pilot)
  File "/home/mturilli/Virtualenvs/stampede2-p3/lib/python3.5/site-packages/radical/pilot/session.py", line 1003, in _get_resource_sandbox
    shell = rsup.PTYShell(js_url, self)
  File "/home/mturilli/Virtualenvs/stampede2-p3/lib/python3.5/site-packages/radical/saga/utils/pty_shell.py", line 244, in __init__
    interactive=self.interactive)
  File "/home/mturilli/Virtualenvs/stampede2-p3/lib/python3.5/site-packages/radical/saga/utils/pty_shell_factory.py", line 199, in initialize
    self._initialize_pty(info['pty'], info)
  File "/home/mturilli/Virtualenvs/stampede2-p3/lib/python3.5/site-packages/radical/saga/utils/pty_shell_factory.py", line 420, in _initialize_pty
    raise ptye.translate_exception (e)
  File "/home/mturilli/Virtualenvs/stampede2-p3/lib/python3.5/site-packages/radical/saga/utils/pty_shell_factory.py", line 319, in _initialize_pty
    % match)
radical.saga.exceptions.AuthenticationFailed: prompted for unknown password (Password: ) (/home/mturilli/Virtualenvs/stampede2-p3/lib/python3.5/site-packages/radical/saga/utils/pty_shell_factory.py +319 (_initialize_pty)  :  % match))
Exception ignored in: <bound method PTYShell.__del__ of <radical.saga.utils.pty_shell.PTYShell object at 0x7f82dc6388d0>>
Traceback (most recent call last):
  File "/home/mturilli/Virtualenvs/stampede2-p3/lib/python3.5/site-packages/radical/saga/utils/pty_shell.py", line 265, in __del__
  File "/usr/lib/python3.5/logging/__init__.py", line 1267, in debug
  File "/usr/lib/python3.5/logging/__init__.py", line 1415, in _log
  File "/usr/lib/python3.5/logging/__init__.py", line 1425, in handle
  File "/usr/lib/python3.5/logging/__init__.py", line 1487, in callHandlers
  File "/usr/lib/python3.5/logging/__init__.py", line 855, in handle
  File "/usr/lib/python3.5/logging/__init__.py", line 1047, in emit
  File "/usr/lib/python3.5/logging/__init__.py", line 1037, in _open
NameError: name 'open' is not defined
Exception ignored in: <bound method PTYProcess.__del__ of <radical.saga.utils.pty_process.PTYProcess object at 0x7f82dc5d7a90>>
Traceback (most recent call last):
  File "/home/mturilli/Virtualenvs/stampede2-p3/lib/python3.5/site-packages/radical/saga/utils/pty_process.py", line 150, in __del__
  File "/usr/lib/python3.5/logging/__init__.py", line 1267, in debug
  File "/usr/lib/python3.5/logging/__init__.py", line 1415, in _log
  File "/usr/lib/python3.5/logging/__init__.py", line 1425, in handle
  File "/usr/lib/python3.5/logging/__init__.py", line 1487, in callHandlers
  File "/usr/lib/python3.5/logging/__init__.py", line 855, in handle
  File "/usr/lib/python3.5/logging/__init__.py", line 1047, in emit
  File "/usr/lib/python3.5/logging/__init__.py", line 1037, in _open
NameError: name 'open' is not defined
```

**Comment by andre-merzky** [comment]
@mturilli : Matteo, I think this should be resolved by now - can we close this one?

**Comment by mturilli** [comment]
Yes, apologies, I should have tracked this myself and closed it before.
