### ISSUE TITLE
JobDescription.Project not supported by radical.saga.adaptors.shell_job

### ISSUE THREAD

**Issue by lee212** [radical-cybertools/radical.saga#755]
radical.log shows the failure:
```
1576610976.944 : pmgr_launching.0000  : 41092 : 140735354630576 : DEBUG    : jd: {'Arguments': ['-l '
               '/ccs/home/hrlee/radical.pilot.sandbox/rp.session.login1.hrlee.018247.0003/bootstrap_0.sh',
               ' -d '
               "'radical.utils-0.90.8-v0.90.3-180-g845001f-devel.tar.gz:radical.saga-0.90.6-bv0.72.1-67-g5deb253-devel.tar.gz:radical.pilot-0.90.8-v0.90.1-190-g9153ccf-devel.tar.gz' "
               "-p 'pilot.0000' -s 'rp.session.login1.hrlee.018247.0003' -m "
               "'create' -r 'local' -b 'default' -g 'default' -v "
               "'/ccs/home/hrlee/radical.pilot.sandbox/ve.local.localhost.0.90.8' "
               "-y '1' -w 'export RP_APP_TUNNEL_ADDR=144.76.72.175:27017' -w "
               "'echo  $RP_APP_TUNNEL_ADDR'"],
 'CandidateHosts': None,
 'Environment': {'RADICAL_PROFILE': 'TRUE'},
 'Error': 'bootstrap_0.err',
 'Executable': '/bin/bash',
 'FileTransfer': [],
 'Name': 'pilot.0000',
 'Output': 'bootstrap_0.out',
 'ProcessesPerHost': 8,
 'Project': 'CSC393',
 'Queue': None,
 'SPMDVariation': None,
 'TotalCPUCount': 8,
 'TotalGPUCount': 2,
 'TotalPhysicalMemory': None,
 'WallTimeLimit': 1,
 'WorkingDirectory': '/ccs/home/hrlee/radical.pilot.sandbox/rp.session.login1.hrlee.018247.0003/pilot.0000/'}
1576610976.948 : radical.saga         : 41092 : 140735354630576 : ERROR    : BadParameter: 'JobDescription.Project' (csc393) not supported by radical.saga.adaptors.shell_job
1576610976.948 : pmgr_launching.0000  : 41092 : 140735354630576 : ERROR    : bulk launch failed
Traceback (most recent call last):
  File "/ccs/home/hrlee/venv3/entk.copy3/lib/python3.7/site-packages/radical/pilot/pmgr/launching/default.py", line 546, in work
    self._start_pilot_bulk(resource, schema, pilots)
  File "/ccs/home/hrlee/venv3/entk.copy3/lib/python3.7/site-packages/radical/pilot/pmgr/launching/default.py", line 776, in _start_pilot_bulk
    jc.add(js.create_job(jd))
  File "/ccs/home/hrlee/venv3/entk.copy3/lib/python3.7/site-packages/radical/saga/job/service.py", line 295, in create_job
    raise se.BadParameter._log (self._logger, msg)
radical.saga.exceptions.BadParameter: 'JobDescription.Project' (csc393) not supported by radical.saga.adaptors.shell_job (/ccs/home/hrlee/venv3/entk.copy3/lib/python3.7/site-packages/radical/saga/job/service.py +295 (create_job)  :  raise se.BadParameter._log (self._logger, msg))
```

```
(entk.copy3) [hrlee@login1.summit radical.saga]$ radical-stack

  python               : 3.7.0
  pythonpath           : /sw/summit/xalt/1.1.4/site:/sw/summit/xalt/1.1.4/libexec
  virtualenv           : /ccs/home/hrlee/venv3/entk.copy3

  radical.entk         : 0.90.6-v0.72.0-84-g5357e08@fix-issue_393
  radical.pilot        : 0.90.8-v0.90.1-190-g9153ccf@devel
  radical.saga         : 0.90.6-bv0.72.1-67-g5deb253@devel
  radical.utils        : 0.90.8-v0.90.3-180-g845001f@devel
```

**Comment by andre-merzky** [comment]
That is expected behavior actually - SAGA adaptors are expected to raise errors on job attributes they cannot interpret, and for the shell adaptor, the notion of a project allocation has no meaning (unlike for batch systems), thus the error...

**Comment by andre-merzky** [comment]
Is this a configuration problem on RP level?  Summit should be configured with `lsf://...`, not with `fork://...` as job submission endpoint?

**Comment by lee212** [comment]
My bad, I accidentally used a wrong endpoint.
