### ISSUE TITLE
`import radical.saga` fails in harvester

### ISSUE THREAD

**Issue by andre-merzky** [radical-cybertools/radical.saga#766]
```
2020-02-10 08:18:59,024 panda.log.queue_config_mapper: ERROR    QueueConfigMapper.load_data : val: {u'name': u'SAGASubmitter', u'adaptor': u'lsf://localhost', u'projectname': u'csc343', u'module': u'pandaharvester.harvestersubmitter.saga_submitter', u'nNodes': 2, u'localqueue': u'batch', u'nCorePerNode': 16}, traceback: Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/zhangr/harvester/x86_envh/lib/python2.7/site-packages/pandaharvester/harvestercore/queue_config_mapper.py", line 465, in load_data
    _t3mP_1Mp0R7_mO6U1e__ = importlib.import_module(val['module'])
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/autofs/nccs-svm1_home1/zhangr/harvester/x86_envh/lib/python2.7/site-packages/pandaharvester/harvestersubmitter/saga_submitter.py", line 2, in <module>
    import radical.saga as saga
  File "/autofs/nccs-svm1_home1/zhangr/harvester/x86_envh/lib/python2.7/site-packages/radical/saga/__init__.py", line 13, in <module>
    import utils
  File "/autofs/nccs-svm1_home1/zhangr/harvester/x86_envh/lib/python2.7/site-packages/radical/saga/utils/__init__.py", line 13, in <module>
    import pty_shell
  File "/autofs/nccs-svm1_home1/zhangr/harvester/x86_envh/lib/python2.7/site-packages/radical/saga/utils/pty_shell.py", line 15, in <module>
    from  .  import misc              as sumisc
ImportError: cannot import name misc
```

We did not yet manage to reproduce the problem outside of Harvester.  Rui suspects that Harvester changes the python environment somewhere in a way that relative import fail.  Absolute imports work though.

**Comment by andre-merzky** [comment]
This is with `v0.72.1`.
