### ISSUE TITLE
radical.saga install fails with virtualenv 15

### ISSUE THREAD

**Issue by iparask** [radical-cybertools/radical.saga#767]
Both @mturilli and I see the following errors when trying to install `radical.saga` as a dependency from `radical.pilot`:

```
(rp-paper-frontera) mturilli@js-156-107:~$ pip install radical.pilot
Collecting radical.pilot
  Using cached radical.pilot-1.1.1.tar.gz (482 kB)
Collecting radical.utils>=1.1
  Using cached radical.utils-1.1.1.tar.gz (146 kB)
Collecting radical.saga>=1.0
  Using cached radical.saga-1.1.1.tar.gz (327 kB)
    ERROR: Command errored out with exit status 1:
     command: /home/mturilli/Virtualenvs/rp-paper-frontera/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-qxa4i8bh/radical.saga/setup.py'"'"'; __file__='"'"'/tmp/pip-install-qxa4i8bh/radical.saga/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-qxa4i8bh/radical.saga/pip-egg-info
         cwd: /tmp/pip-install-qxa4i8bh/radical.saga/
    Complete output (11 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/mturilli/Virtualenvs/rp-paper-frontera/lib/python3.7/site-packages/setuptools/__init__.py", line 5, in <module>
        import distutils.core
      File "/home/mturilli/Virtualenvs/rp-paper-frontera/lib/python3.7/distutils/__init__.py", line 4, in <module>
        import imp
      File "/tmp/pip-install-qxa4i8bh/radical.saga/imp.py", line 7, in <module>
        m = importlib.import_module('radical.pilot')
      File "/home/mturilli/Virtualenvs/rp-paper-frontera/lib/python3.7/importlib/__init__.py", line 127, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
    ModuleNotFoundError: No module named 'radical'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

```
(test_install) [paraskev@login006 ~]$ pip install radical.pilot
Collecting radical.pilot
  Downloading radical.pilot-1.1.1.tar.gz (482 kB)
     |████████████████████████████████| 482 kB 2.3 MB/s
Collecting radical.utils>=1.1
  Downloading radical.utils-1.1.1.tar.gz (146 kB)
     |████████████████████████████████| 146 kB 62.7 MB/s
Collecting radical.saga>=1.0
  Downloading radical.saga-1.1.1.tar.gz (327 kB)
     |████████████████████████████████| 327 kB 56.9 MB/s
    ERROR: Command errored out with exit status 1:
     command: /home/paraskev/test_install/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-_vqmwbka/radical.saga/setup.py'"'"'; __file__='"'"'/tmp/pip-install-_vqmwbka/radical.saga/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-_vqmwbka/radical.saga/pip-egg-info
         cwd: /tmp/pip-install-_vqmwbka/radical.saga/
    Complete output (11 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/paraskev/test_install/lib/python3.5/site-packages/setuptools/__init__.py", line 5, in <module>
        import distutils.core
      File "/home/paraskev/test_install/lib/python3.5/distutils/__init__.py", line 4, in <module>
        import imp
      File "/tmp/pip-install-_vqmwbka/radical.saga/imp.py", line 7, in <module>
        m = importlib.import_module('radical.pilot')
      File "/home/paraskev/test_install/lib/python3.5/importlib/__init__.py", line 126, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
    ImportError: No module named 'radical'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
(test_install) [paraskev@login006 ~]$ deactivate
```

**Comment by andre-merzky** [comment]
This usually is a problem in setuptools, and upgrading it should help.  If it persists, can you please provide the resource and steps to reproduce it?  Thanks!

**Comment by iparask** [comment]
Yes, here they are:
```
[paraskev@login005 ~]$ module load python3
[paraskev@login005 ~]$ virtualenv test_install
Using base prefix '/opt/packages/python/Python-3.5.2-icc-mkl'
New python executable in /home/paraskev/test_install/bin/python3
Also creating executable in /home/paraskev/test_install/bin/python
Installing setuptools, pip, wheel...done.
[paraskev@login005 ~]$ source test_install/bin/activate
(test_install) [paraskev@login005 ~]$ export PYTHONPATH=/home/paraskev/test_install/lib/python3.5/site-packages/:$PYTHONPATH
(test_install) [paraskev@login005 ~]$ pip install setuptools --upgrade
Requirement already up-to-date: setuptools in ./test_install/lib/python3.5/site-packages (45.2.0)
(test_install) [paraskev@login005 ~]$ pip install --no-cache-dir radical.pilot
Collecting radical.pilot
  Downloading radical.pilot-1.1.1.tar.gz (482 kB)
     |████████████████████████████████| 482 kB 2.1 MB/s
Collecting radical.utils>=1.1
  Downloading radical.utils-1.1.1.tar.gz (146 kB)
     |████████████████████████████████| 146 kB 62.2 MB/s
Collecting radical.saga>=1.0
  Downloading radical.saga-1.1.1.tar.gz (327 kB)
     |████████████████████████████████| 327 kB 56.7 MB/s
    ERROR: Command errored out with exit status 1:
     command: /home/paraskev/test_install/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-asi9sqsy/radical.saga/setup.py'"'"'; __file__='"'"'/tmp/pip-install-asi9sqsy/radical.saga/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-asi9sqsy/radical.saga/pip-egg-info
         cwd: /tmp/pip-install-asi9sqsy/radical.saga/
    Complete output (11 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/paraskev/test_install/lib/python3.5/site-packages/setuptools/__init__.py", line 5, in <module>
        import distutils.core
      File "/home/paraskev/test_install/lib/python3.5/distutils/__init__.py", line 4, in <module>
        import imp
      File "/tmp/pip-install-asi9sqsy/radical.saga/imp.py", line 7, in <module>
        m = importlib.import_module('radical.pilot')
      File "/home/paraskev/test_install/lib/python3.5/importlib/__init__.py", line 126, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
    ImportError: No module named 'radical'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
(test_install) [paraskev@login005 ~]$
```

**Comment by andre-merzky** [comment]
Oy, this is the point where I also should point out that our stack requires Python 3.6!  Is such a python module available on bridges?

**Comment by iparask** [comment]
I would like to point to two things:

- The setup file requires at least python 3.5:

```
# ------------------------------------------------------------------------------
# check python version. we need >= 2.7, <3.x
if  sys.hexversion <= 0x03050000:
    raise RuntimeError('%s requires Python 3.5 or higher' % name)
```

- Bridges python3.6 module does not have virtualenv:
```
********************************* W A R N I N G ********************************
[paraskev@login018 ~]$ module load python3/intel_3.6.2
[paraskev@login018 ~]$ which virtualenv
/usr/bin/which: no virtualenv in (/opt/intel/python_2018.0.022/intelpython3/bin:/usr/lib64/qt-3.3/bin:/opt/packages/xdusage/2.1-1/bin:/opt/intel/advisor_2019.5.0.602216/bin64:/opt/intel/vtune_amplifier_2019.6.0.602217/bin64:/opt/intel/inspector_2019.5.0.602103/bin64:/opt/intel/itac/2019.5.041/intel64/bin:/opt/intel/clck/2019.5/bin/intel64:/opt/intel/compilers_and_libraries_2019.5.281/linux/bin/intel64:/opt/intel/compilers_and_libraries_2019.5.281/linux/mpi/intel64/libfabric/bin:/opt/intel/compilers_and_libraries_2019.5.281/linux/mpi/intel64/bin:/opt/intel/debugger_2019/gdb/intel64/bin:/opt/packages/slurm/default/bin:/opt/packages/allocations:/opt/packages/interact/bin:/usr/lib64/ccache:/usr/local/bin:/bin:/usr/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/puppetlabs/puppet/bin:/opt/intel/parallel_studio_xe_2019.5.075/bin:/bin:/sbin:/opt/puppetlabs/bin:/home/paraskev/.local/bin:/home/paraskev/bin)
[paraskev@login018 ~]$ module avail
```

Either way, I think that the setup file should reflect the dependency correctly. And I will check what can be done on Bridges. I used Bridges, because any other system I have uses conda and I wanted a clean from conda environment.

**Comment by andre-merzky** [comment]
Ack on setup.py, that's a change that is incoming into devel.  As of not having virtualenv: would `python3 -m venv ve/` work?

**Comment by andre-merzky** [comment]
RS's `MANIFEST.in` was to generous, and picked up a file which conflicted with an internal module.  I am not sure *how* it could actually conflict, it living outside of the installation source, but whatever.  I pushed a hotfix release which rstricts `MANIFEST.in`, and install works again.
