### ISSUE TITLE
Cannot load libcloud (radical.saga.adaptors.aws.ec2_resource)

### ISSUE THREAD

**Issue by mtitov** [radical-cybertools/radical.saga#772]
This error doesn't affect the current workflow, just appears in log:

**machine**: longhorn.tacc.utexas.edu
```
$ cat /scratch/07151/tg864504/radical.pilot.sandbox/rp.session.login2.longhorn.tacc.utexas.edu.tg864504.018337.0001/pilot.0000/radical.saga.log

1584376122.506 : radical.saga         : 100060 : 35184372375920 : INFO     : radical.saga         version: 1.2.0
1584376122.506 : radical.saga         : 100060 : 35184372375920 : DEBUG    : listing  adaptor registry: {'adaptor_registry': ['radical.saga.adaptors.context.myproxy', 'radical.saga.adaptors.context.x509', 'radical.saga.adaptors.context.ssh', 'radical.saga.adaptors.context.userpass', 'radical.saga.adaptors.noop.noop_job', 'radical.saga.adaptors.shell.shell_job', 'radical.saga.adaptors.shell.shell_file', 'radical.saga.adaptors.shell.shell_resource', 'radical.saga.adaptors.redis.redis_advert', 'radical.saga.adaptors.sge.sgejob', 'radical.saga.adaptors.lsf.lsfjob', 'radical.saga.adaptors.condor.condorjob', 'radical.saga.adaptors.slurm.slurm_job', 'radical.saga.adaptors.http.http_file', 'radical.saga.adaptors.aws.ec2_resource', 'radical.saga.adaptors.loadl.loadljob', 'radical.saga.adaptors.globus_online.go_file', 'radical.saga.adaptors.torque.torquejob', 'radical.saga.adaptors.pbspro.pbsprojob', 'radical.saga.adaptors.srm.srmfile', 'radical.saga.adaptors.cobalt.cobaltjob']}
...
1584376122.596 : radical.saga         : 100060 : 35184372375920 : INFO     : loading  adaptor radical.saga.adaptors.aws.ec2_resource
1584376122.599 : radical.saga         : 100060 : 35184372375920 : WARNING  : skip adaptor radical.saga.adaptors.aws.ec2_resource: test failed
Traceback (most recent call last):
  File "/scratch/07151/tg864504/radical.pilot.sandbox/rp.session.login2.longhorn.tacc.utexas.edu.tg864504.018337.0001/pilot.0000/rp_install/lib/python3.8/site-packages/radical/saga/adaptors/aws/ec2_resource.py", line 144, in sanity_check
    self.lc   = __import__ ('libcloud',                   fromlist=[''])
ModuleNotFoundError: No module named 'libcloud'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/07151/tg864504/radical.pilot.sandbox/rp.session.login2.longhorn.tacc.utexas.edu.tg864504.018337.0001/pilot.0000/rp_install/lib/python3.8/site-packages/radical/saga/engine/engine.py", line 207, in _load_adaptors
    adaptor_instance.sanity_check ()
  File "/scratch/07151/tg864504/radical.pilot.sandbox/rp.session.login2.longhorn.tacc.utexas.edu.tg864504.018337.0001/pilot.0000/rp_install/lib/python3.8/site-packages/radical/saga/adaptors/aws/ec2_resource.py", line 178, in sanity_check
    raise rse.NoSuccess ("Cannot load libcloud")
radical.saga.exceptions.NoSuccess: Cannot load libcloud (/scratch/07151/tg864504/radical.pilot.sandbox/rp.session.login2.longhorn.tacc.utexas.edu.tg864504.018337.0001/pilot.0000/rp_install/lib/python3.8/site-packages/radical/saga/adaptors/aws/ec2_resource.py +178 (sanity_check)  :  raise rse.NoSuccess ("Cannot load libcloud"))
...

$ radical-stack 

  python               : 3.8.1
  pythonpath           : 
  virtualenv           : /home/07151/tg864504/ve

  radical.pilot        : 1.2.1-v1.2.1-10-g4bf4dbd3@devel
  radical.saga         : 1.2.0
  radical.utils        : 1.2.0
```

**Comment by mtitov** [comment]
This was resolved
